<a href="https://colab.research.google.com/github/shane-harris/Stock_Price_Predictor/blob/master/Stock_tfidf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
pd.core.common.is_list_like = pd.api.types.is_list_like
import matplotlib.pyplot as ply
% matplotlib inline
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [ ]:
df = pd.read_csv(r'/content/drive/My Drive/CSC 180/Final Project/Practice Data/Copy of all_news_stock_dateformated.csv')

In [ ]:
df.shape

(18585, 6)

In [ ]:
df_copy = df
df.head()

   Unnamed: 0  ...                                              title
0           0  ...  Factbox: How social media services handle poli...
1           1  ...  Facebook, Google 'surveillance' threatens huma...
2           2  ...  Facebook to introduce new safety tools for adv...
3           3  ...  Bulls and Bears Can Bite Into These FANG Stock...
4           4  ...        Top Communications Stocks for December 2019

[5 rows x 6 columns]

In [ ]:
df_sent = pd.get_dummies(df_copy, columns=['sentiment'])
df_sent.drop(['Unnamed: 0'], axis=1)

      Ticker         date  ... sentiment_Neutral sentiment_Positive
0         FB  2019-11-20   ...                 1                  0
1         FB  2019-11-20   ...                 0                  0
2         FB  2019-11-20   ...                 0                  1
3         FB  2019-11-20   ...                 1                  0
4         FB  2019-11-20   ...                 0                  1
...      ...          ...  ...               ...                ...
18580    XOM  2019-11-01   ...                 0                  1
18581    XOM  2019-11-01   ...                 0                  0
18582    XOM  2019-11-01   ...                 0                  0
18583    XOM  2019-11-01   ...                 1                  0
18584    XOM  2019-11-01   ...                 0                  0

[18585 rows x 7 columns]

In [ ]:
df_sent

       Unnamed: 0 Ticker  ... sentiment_Neutral sentiment_Positive
0               0     FB  ...                 1                  0
1               1     FB  ...                 0                  0
2               2     FB  ...                 0                  1
3               3     FB  ...                 1                  0
4               4     FB  ...                 0                  1
...           ...    ...  ...               ...                ...
18580          45    XOM  ...                 0                  1
18581          46    XOM  ...                 0                  0
18582          47    XOM  ...                 0                  0
18583          48    XOM  ...                 1                  0
18584          49    XOM  ...                 0                  0

[18585 rows x 8 columns]

In [ ]:
# df_agg = {'Ticker': 'first','text': df_sent.agg(['text']), 'title': df_sent.agg(['title']),  'sentiment_Negative': 'sum', 'sentiment_Neutral': 'sum', 'sentiment_Positive': 'sum'}
# df_agg = {'Ticker': 'first', 'sentiment_Negative': 'sum', 'sentiment_Neutral': 'sum', 'sentiment_Positive': 'sum'}
df_agg = {'date':'first','Ticker': 'first','text': 'first', 'title': 'first', 'sentiment_Negative': 'sum', 'sentiment_Neutral': 'sum', 'sentiment_Positive': 'sum'}
# df_txt_titl = pd.DataFrame({'df_sent':title, 'df_sent':text})
# text = pd.Series(df_sent['text'])
# df_new = df_sent.groupby(['Ticker','date'])['text','title'].apply(''.join).aggregate(df_agg).reset_index()
# df_new = df_sent.groupby(['Ticker','date'])[df_sent['text'], df_sent['title']].apply(' '.join).reset_index()
# df_new = df_sent.groupby(['Ticker','date']).apply(lambda x: x.combine_first(df_sent['text'], axis=1).combine_first(df_sent['title'], axis=1))

df_new = df_sent.groupby(['Ticker','date']).aggregate(df_agg)

In [ ]:
df_new.reset_index(inplace=True,drop=True)

df_new

             date Ticker  ... sentiment_Neutral sentiment_Positive
0     2018-11-22    AAPL  ...                 4                  0
1     2018-11-25    AAPL  ...                 4                  0
2     2018-11-26    AAPL  ...                 4                  0
3     2018-11-27    AAPL  ...                 5                  0
4     2018-11-28    AAPL  ...                 3                  0
...           ...    ...  ...               ...                ...
3802  2019-11-14     XOM  ...                 1                  0
3803  2019-11-16     XOM  ...                 1                  0
3804  2019-11-17     XOM  ...                 1                  1
3805  2019-11-19     XOM  ...                 0                  2
3806  2019-11-20     XOM  ...                 1                  1

[3807 rows x 7 columns]

In [ ]:
df_new.iloc[0, df_new.columns.get_loc('sentiment_Neutral')]

4

In [ ]:

df_new['sentiment_Negative'] = df_new['sentiment_Negative'].astype(float)
df_new['sentiment_Neutral'] = df_new['sentiment_Neutral'].astype(float)
df_new['sentiment_Positive'] = df_new['sentiment_Positive'].astype(float)
# total =0
# for index, dfs in df_new.iterrows():
#   total = dfs['sentiment_Negative'] + dfs['sentiment_Neutral'] + dfs['sentiment_Positive']
#   # print(total)
#   # print(dfs['sentiment_Negative']/total)
#   neg = dfs['sentiment_Negative']/total
#   # print(neg)
#   neu = dfs['sentiment_Neutral']/total
#   pos = dfs['sentiment_Positive']/total
#   # df_new.at[dfs, 'sentiment_Negative'] = neg
#   df_new.set_value(dfs,'sentiment_Neutral',neu)
#   # df_new.set_value(dfs,'sentiment_Positive',pos)
#   # print(dfs['sentiment_Negative'])

for i in range(len(df_new)):
  df_new.loc[i,'sentiment_Negative'] = (df_new.loc[i,'sentiment_Negative'])/(df_new.loc[i,'sentiment_Negative']+df_new.loc[i,'sentiment_Neutral']+df_new.loc[i,'sentiment_Positive'])
  df_new.loc[i,'sentiment_Neutral'] = (df_new.loc[i,'sentiment_Neutral'])/(df_new.loc[i,'sentiment_Negative']+df_new.loc[i,'sentiment_Neutral']+df_new.loc[i,'sentiment_Positive'])
  df_new.loc[i,'sentiment_Positive'] = (df_new.loc[i,'sentiment_Positive'])/(df_new.loc[i,'sentiment_Negative']+df_new.loc[i,'sentiment_Neutral']+df_new.loc[i,'sentiment_Positive'])

# df_new.replace(to_replace=df_new['sentiment_Negative'], value=(df_new['sentiment_Negative']/(df_new['sentiment_Negative']+df_new['sentiment_Neutral']+df_new['sentiment_Positive'])))
# df_new.replace(to_replace=df_new['sentiment_Neutral'], value=(df_new['sentiment_Neutral']/(df_new['sentiment_Negative']+df_new['sentiment_Neutral']+df_new['sentiment_Positive'])))
# df_new.replace(to_replace=df_new['sentiment_Positive'], value=(df_new['sentiment_Positive']/(df_new['sentiment_Negative']+df_new['sentiment_Neutral']+df_new['sentiment_Positive'])))


df_new.head(500)

            date Ticker  ... sentiment_Neutral sentiment_Positive
0    2018-11-22    AAPL  ...               1.0                0.0
1    2018-11-25    AAPL  ...               1.0                0.0
2    2018-11-26    AAPL  ...               1.0                0.0
3    2018-11-27    AAPL  ...               1.0                0.0
4    2018-11-28    AAPL  ...               1.0                0.0
..           ...    ...  ...               ...                ...
495  2019-11-06     BBY  ...               0.0                1.0
496  2019-11-11     BBY  ...               0.0                0.0
497  2019-11-14     BBY  ...               0.0                1.0
498  2019-11-19     BBY  ...               0.0                1.0
499  2019-08-15    CASI  ...               0.0                1.0

[500 rows x 7 columns]

In [ ]:
# df_copy.drop(['sentiment', 'Unnamed: 0'], axis=1)

In [ ]:
# df_copy.head(1).combine_first(df_copy.tail(1))

In [ ]:
# df_copy

In [ ]:
text_list = list(df_new['text'])
title_list = list(df_new['title'])

In [ ]:
vectorizer1 = TfidfVectorizer(ngram_range=(1,1), max_features=500)
vectorizer2 = TfidfVectorizer(ngram_range=(1,1), max_features=500)

In [ ]:
text_x = vectorizer1.fit_transform(text_list)
title_x = vectorizer2.fit_transform(title_list)

In [ ]:
print(vectorizer2.get_feature_names())

['000', '10', '11', '13', '20', '2019', '2020', '500', 'about', 'ad', 'add', 'aegion', 'aegn', 'after', 'again', 'against', 'ahead', 'ai', 'all', 'alliant', 'ally', 'alphabet', 'amazon', 'amid', 'an', 'analyst', 'analysts', 'and', 'announces', 'another', 'antitrust', 'app', 'apple', 'april', 'are', 'armour', 'as', 'at', 'august', 'auto', 'back', 'based', 'bby', 'be', 'beat', 'before', 'best', 'bet', 'better', 'beyond', 'big', 'biggest', 'bill', 'billion', 'block', 'board', 'boost', 'break', 'buffett', 'bull', 'bullish', 'business', 'but', 'buy', 'buying', 'buys', 'by', 'cabot', 'california', 'call', 'calls', 'can', 'cap', 'capital', 'car', 'cars', 'cash', 'cbs', 'ceo', 'change', 'charts', 'chief', 'china', 'chipotle', 'cloud', 'cmg', 'co', 'cog', 'coming', 'companies', 'company', 'competition', 'concho', 'consumer', 'content', 'continue', 'continues', 'contract', 'cook', 'corp', 'corporation', 'cost', 'costco', 'could', 'coup', 'coupa', 'court', 'cramer', 'credit', 'cryptocurrency', 'customers', 'cuts', 'cxo', 'data', 'day', 'deal', 'decline', 'delivery', 'demand', 'despite', 'digital', 'dips', 'dish', 'disney', 'dividend', 'do', 'does', 'don', 'dow', 'down', 'drive', 'driving', 'drop', 'earnings', 'ecpg', 'electric', 'elon', 'employees', 'encore', 'energy', 'erie', 'estimates', 'even', 'expect', 'expected', 'expert', 'faang', 'face', 'facebook', 'faces', 'fake', 'fang', 'fast', 'final', 'financial', 'first', 'five', 'focus', 'food', 'for', 'former', 'founder', 'free', 'friday', 'from', 'ftc', 'fund', 'future', 'gains', 'game', 'gas', 'get', 'gets', 'getting', 'giants', 'global', 'gm', 'go', 'going', 'goldman', 'good', 'googl', 'google', 'great', 'grill', 'group', 'grow', 'growing', 'growth', 'half', 'has', 'have', 'he', 'health', 'healthcare', 'help', 'here', 'hershey', 'high', 'higher', 'highs', 'his', 'hit', 'hits', 'hold', 'holiday', 'home', 'how', 'hrb', 'huawei', 'huge', 'if', 'illumina', 'ilmn', 'in', 'inc', 'income', 'industry', 'instagram', 'international', 'into', 'invest', 'investigation', 'investing', 'investment', 'investor', 'investors', 'iphone', 'is', 'isn', 'it', 'its', 'jaffray', 'jim', 'jones', 'judge', 'july', 'jumped', 'june', 'just', 'keep', 'key', 'know', 'lags', 'large', 'last', 'latest', 'launch', 'launches', 'lawsuit', 'libra', 'like', 'likely', 'list', 'logistics', 'long', 'look', 'looks', 'low', 'make', 'makes', 'making', 'mark', 'market', 'markets', 'may', 'mcd', 'mcdonald', 'media', 'merger', 'mexican', 'microsoft', 'might', 'million', 'mixed', 'mobile', 'model', 'momentum', 'money', 'more', 'most', 'move', 'moves', 'msft', 'much', 'musk', 'must', 'natural', 'need', 'netflix', 'network', 'new', 'news', 'next', 'no', 'not', 'now', 'oceanfirst', 'ocfc', 'of', 'off', 'office', 'oil', 'on', 'one', 'online', 'open', 'option', 'options', 'or', 'oracle', 'orcl', 'other', 'out', 'outlook', 'over', 'own', 'part', 'partners', 'partnership', 'pay', 'pcg', 'people', 'pg', 'pick', 'picks', 'pinnacle', 'piper', 'plan', 'plans', 'pnfp', 'political', 'portfolio', 'potential', 'power', 'president', 'preview', 'price', 'prices', 'privacy', 'pro', 'probe', 'production', 'push', 'q1', 'q2', 'q3', 'q4', 'quarter', 'rally', 'ranked', 'rate', 'reasons', 'rebound', 'recession', 'record', 'report', 'reportedly', 'reports', 'resources', 'restaurant', 'results', 'retail', 'retailers', 'revenue', 'revenues', 'right', 'rise', 'risk', 'run', 'sales', 'say', 'says', 'season', 'sec', 'second', 'sector', 'see', 'sees', 'self', 'sell', 'september', 'service', 'services', 'set', 'share', 'shares', 'shopping', 'short', 'should', 'show', 'shows', 'since', 'so', 'social', 'software', 'solar', 'sold', 'solid', 'some', 'stanley', 'steve', 'still', 'stock', 'stocks', 'store', 'stores', 'strategy', 'streaming', 'street', 'strong', 'take', 'takes', 'talks', 'target', 'tariffs', 'tax', 'tech', 'technology', 'telus', 'term', 'tesla', 'tgt', 'than', 'that', 'the', 'their', 'there', 'these', 'they', 'things', 'this', 'three', 'through', 'thursday', 'tim', 'time', 'to', 'today', 'too', 'top', 'toyota', 'trade', 'traders', 'trades', 'transcript', 'trump', 'tu', 'tuesday', 'tv', 'twitter', 'two', 'under', 'undervalued', 'union', 'up', 'upside', 'us', 'users', 'utility', 'value', 'vehicles', 'viacom', 'video', 'vs', 'wall', 'walmart', 'wants', 'war', 'warren', 'wars', 'was', 'watch', 'water', 'waymo', 'we', 'wednesday', 'week', 'western', 'what', 'where', 'which', 'who', 'wholesale', 'why', 'will', 'win', 'winners', 'with', 'won', 'world', 'worth', 'wu', 'xbox', 'year', 'years', 'you', 'your', 'youtube', 'zuckerberg']

In [ ]:
df1 = pd.DataFrame(text_x.toarray(), columns=vectorizer1.get_feature_names())
df2 = pd.DataFrame(title_x.toarray(), columns=vectorizer2.get_feature_names())

In [ ]:
sub_df = df_new[['Ticker','date','sentiment_Negative','sentiment_Neutral','sentiment_Positive']]

In [ ]:
sub_df

     Ticker         date  ...  sentiment_Neutral  sentiment_Positive
0      AAPL  2018-11-22   ...                1.0            0.000000
1      AAPL  2018-11-25   ...                1.0            0.000000
2      AAPL  2018-11-26   ...                1.0            0.000000
3      AAPL  2018-11-27   ...                1.0            0.000000
4      AAPL  2018-11-28   ...                1.0            0.000000
...     ...          ...  ...                ...                 ...
3802    XOM  2019-11-14   ...                1.0            0.000000
3803    XOM  2019-11-16   ...                1.0            0.000000
3804    XOM  2019-11-17   ...                0.5            0.666667
3805    XOM  2019-11-19   ...                0.0            1.000000
3806    XOM  2019-11-20   ...                0.5            0.666667

[3807 rows x 5 columns]

In [ ]:
new_df = pd.concat([sub_df, df1],axis=1)

In [ ]:
new_df1 = pd.concat([new_df,df2], axis=1)

In [ ]:
new_df1.head()

  Ticker         date  sentiment_Negative  ...  your  youtube  zuckerberg
0   AAPL  2018-11-22                  0.0  ...   0.0      0.0         0.0
1   AAPL  2018-11-25                  0.0  ...   0.0      0.0         0.0
2   AAPL  2018-11-26                  0.0  ...   0.0      0.0         0.0
3   AAPL  2018-11-27                  0.0  ...   0.0      0.0         0.0
4   AAPL  2018-11-28                  0.0  ...   0.0      0.0         0.0

[5 rows x 1005 columns]

In [ ]:
new_df1.to_csv(r'/content/drive/My Drive/CSC 180/Final Project/Practice Data/one_hot_and_tfidf.csv')